# Good Gaussian elimination

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Johnson Li</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

##### Overview
Given a matrix with finite rows and finite columns, Good Gaussion Elimination aims to reduce a matrix into its upper triangular form within as less time as it could. 

##### Algorithm
1. Create an $N\times M$ matrix that you what to reduce.
> $A=\begin{bmatrix}X_{1,1}& \cdots & X_{1,M} \\ \vdots & \vdots & \vdots \\ X_{N,1} & \cdots& X_{N,M} \end{bmatrix}$
2. Then compute a upper triangular matrix
> $A'=\begin{bmatrix}Y_{1,1}& \cdots & Y_{1,M} \\ \vdots & \vdots & \vdots \\ 0 & \cdots& Y_{N,M} \end{bmatrix}$

##### Implementation

In [1]:
##########
## MAIN ##
##########

##algorithm part
def gauss_eli(A):
    n,m=A.dimensions()
    c=0
    d=[]
    for k in range(0,m):
        t=0
        for i in range(0,n):
            if((A[i,k] != 0) and (t != 1) and (i not in d)):
                t=1
                d=d+[i]
                for j in range(0,n):
                    if(j != i):
                        A[j,0:] = A[j,0:]*A[i,k]-A[i,0:]*A[j,k]
    #answer
    #return A

    #rearrange
    AR = copy(A)
    for p in range(0,m):
        if(p not in d):
            d=d+[p]
    for l in range(0,n):
            AR[l,0:]=A[d[l],0:]
    return AR





##Trials
import numpy as np
a=matrix(np.random.rand(3,4)*10)
a=matrix([[3,3,3],[2,2,2],[4,4,4]])
a=matrix([[0,0,-2,1],[2,2,2,1],[-2,0,0,1]])
print "original matrix"
print a
print '---'
b=copy(a)
print "my answer"
print gauss_eli(a)
print "---"
print "sage default answer"
print b.echelon_form()

original matrix
[ 0  0 -2  1]
[ 2  2  2  1]
[-2  0  0  1]
---
my answer
[-128    0    0   64]
[   0  -64    0  -96]
[   0    0  -16    8]
---
sage default answer
[ 2  0  0 -1]
[ 0  2  0  3]
[ 0  0  2 -1]


In [2]:
A = matrix(QQ, [
    [0,0,1],
    [0,1,1],
    [1,1,0]
])

In [3]:
gauss_eli(A)

[1 0 0]
[0 1 0]
[0 0 1]

In [4]:
A.echelon_form()

[1 0 0]
[0 1 0]
[0 0 1]