# Minimal Polynomial

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">陳政廷</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

### Overview

#### **Cayley&ndash;Hamilton定理**:
- $A$ 為一個 $n\times n$ 階矩陣且 $p(t)$ 為 $A$ 的特徵多項式( $p(t)=\det(A-tI)$ )。將矩陣 $A$ 替換 $t$ 得到的矩陣多項式滿足 $p(A)=O$。

#### **最小多項式** $m_A(t)$:
 1. 滿足 $p(A)=O$ 的方程式中次數為最小者
 2. 最高次項係數為1

#### **最小多項式的重要性質**:
 1. $A$ 之所有的特徵值 $λ_i$ 皆使 $m_A(λ_i)=0$
 2. 若 $p(t)=(t-λ_1)^{m_1}\times(t-λ_2)^{m_2}\times\cdots\times(t-λ_k)^{m_k},m_{1}+m_{2}+‧‧‧m_{k}=n$  
 則 $m_A(t)=(t-λ_1)^{d_1}\times(t-λ_2)^{d_2}\times\cdots\times(t-λ_k)^{d_k}, 1 \leq d_i \leq m_i$, $\forall i$ 
 3. $A$ 可對角化 $\iff$ $m_A(t)=(t-λ_1)\times(t-λ_2)\times\cdots\times(t-λ_k)$；  i.e 最小多項式沒有重根

### Algorithm



Computer $I,A,\ldots,A^{n}$ and flaten them into vectors in $\mathbb{R}^{n^2}$.  Find the smallest $k$ such that $\{I,A,\ldots,A^k\}$ is dependent.  
Suppose $A = \begin{bmatrix}a_{i,j}\end{bmatrix}$.  You may flatten them as a vector $f(A) = (a_{1,1},\ldots, a_{1,n},a_{2,1}\ldots,a_{n,n})$ in $\mathbb{R}^{n^2}$  
Create a huge matrix $H$ whose columns are $f(I),f(A),\ldots,f(A^{n-1})$ and do Gaussian elimination on $H$.
Find the minimum $k$ such that $\{f(I),f(A),\ldots,f(A^k)\}$ is dependent.  
Find coefficients so that $a_kf(A^k)+\ldots a_0f(I)=0$ and $a_k=1$.  
Thus $a_kA^k+\ldots a_0I=O$ and $m(t)=a_kt^k+\cdots+a_0$ is the minimal polynomial.




### Explanation
判斷$A_{n\times n}$是否可對角化

>$p(t)=det(A-tI)=(t-λ_1)^{m_1}\times(t-λ_2)^{m_2}\times\cdots\times(t-λ_k)^{m_k}$ 

找出$p(t)$的最小多項式$m_A(t)$使得$m_A(A)=0$  
如果$m_A(t)$中$(t-λ_i)$的次數皆為1次，則A為可對角化  
如果$m_A(t)$中其中一項$(t-λ_i)^k,2\leq k$，則A為不可對角化



##### Implementation

In [1]:
def minimalpolynomial(data):
    """
    Input:
        data:  給定一方陣A
    Output:
        Output 最小多項式 m_A(t) 中沒有重根，則方陣A為可對角化。
    """
    data.change_ring(QQ)
    m,n = data.dimensions()
    if (m == n):
        I = identity_matrix(n)                                     #單位矩陣
        flattened_I = [I[i,j] for i in range(m) for j in range(n)] #攤平單位矩陣
        flattened_data = [flattened_I] #將I存成[I]
   
        for k in range(1,m+1):
            data_i=data^k
            flattened_data_i= [data_i[i,j] for i in range(m) for j in range(n)] #data^k矩陣攤平
            flattened_data.append(flattened_data_i) #將矩陣變為[I,data^1,...,data^k]
        M = matrix(flattened_data).transpose() 
        show(M)
       
        r = M.rank()
        sliced_M = M[:,0:r+1]
        show(sliced_M)
        factor=sliced_M.right_kernel()
        show(factor.basis()[0])
        A=matrix(factor.basis()[0])
        
        
        
        poly=0 
        for k in range(0,r+1):    #取出係數將其變為一多項式
            item=x^k*A[0,k]
            poly+=item
        if(A[0,r]<0):             #讓首項系數為1
            poly*=-1
        return poly
           
    else:
        print'data is not square matrix'

def diagonalizable(data):
    poly=minimalpolynomial(data)
    show(poly)
    polyprime=poly.derivative()
    show(polyprime)
    poly.gcd(polyprime)
    show(poly.gcd(polyprime))
    if (poly.gcd(polyprime)==1):
        print'The square matrix is diagonalizable'   # If p and pprime has common factor other than 1, then p is not square free
    else:
        print'The square matrix is non-diagonalizable'

        
        


##### Examples

In [2]:
### diagonalizable
data= matrix([[3,-3,2],[-1,5,-2],[-1,3,0]])
diagonalizable(data)


[  1   3  10  36]
[  0  -3 -18 -84]
[  0   2  12  56]
[  0  -1  -6 -28]
[  1   5  22  92]
[  0  -2 -12 -56]
[  0  -1  -6 -28]
[  0   3  18  84]
[  1   0  -8 -48]

[  1   3  10]
[  0  -3 -18]
[  0   2  12]
[  0  -1  -6]
[  1   5  22]
[  0  -2 -12]
[  0  -1  -6]
[  0   3  18]
[  1   0  -8]

(8, -6, 1)

x^2 - 6*x + 8

2*x - 6

1

The square matrix is diagonalizable


In [3]:
### random matrix diagonalizable
import numpy as np
data= matrix(np.random.randint(0,500,[4,4]))
diagonalizable(data)

[           1          241       100765    100140337  85215895648]
[           0          121       111486    106373851  85047493689]
[           0          403       256524    153400684 119105282037]
[           0           46       133905    108442063  79157034675]
[           0           83       122562    103291053  78342776619]
[           1          174       133186    101933165  77846413204]
[           0          271       168613    140586233 114875619034]
[           0          182       131215     92764856  72658970185]
[           0           31       126824    105906236  77208864533]
[           0          113       136987    101990395  76383908518]
[           1          312       144811    135994876 114441983923]
[           0          229       135805     89051182  71051234020]
[           0          438       215563    128340085 104942141941]
[           0          342       177923    129898988 107422019453]
[           0           19       278639    224322782 159353608592]
[           1          185       120968    128485295 104684956379]

[           1          241       100765    100140337  85215895648]
[           0          121       111486    106373851  85047493689]
[           0          403       256524    153400684 119105282037]
[           0           46       133905    108442063  79157034675]
[           0           83       122562    103291053  78342776619]
[           1          174       133186    101933165  77846413204]
[           0          271       168613    140586233 114875619034]
[           0          182       131215     92764856  72658970185]
[           0           31       126824    105906236  77208864533]
[           0          113       136987    101990395  76383908518]
[           1          312       144811    135994876 114441983923]
[           0          229       135805     89051182  71051234020]
[           0          438       215563    128340085 104942141941]
[           0          342       177923    129898988 107422019453]
[           0           19       278639    224322782 159353608592]
[           1          185       120968    128485295 104684956379]

(2414326200, -54066099, 166007, -912, 1)

x^4 - 912*x^3 + 166007*x^2 - 54066099*x + 2414326200

4*x^3 - 2736*x^2 + 332014*x - 54066099

1

The square matrix is diagonalizable


In [4]:
### non-diagonalizable
data = matrix([[1,-1],[1,3]])
diagonalizable(data)

[ 1  1  0]
[ 0 -1 -4]
[ 0  1  4]
[ 1  3  8]

[ 1  1  0]
[ 0 -1 -4]
[ 0  1  4]
[ 1  3  8]

(4, -4, 1)

x^2 - 4*x + 4

2*x - 4

2*x - 4

The square matrix is non-diagonalizable


In [5]:
### non-diagonalizable  
data =matrix([[1,0,0,0],[0,2,0,0],[0,0,4,1],[0,0,0,4]])
diagonalizable(data)


[  1   1   1   1   1]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   2   4   8  16]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   4  16  64 256]
[  0   1   8  48 256]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   4  16  64 256]

[  1   1   1   1   1]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   2   4   8  16]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   4  16  64 256]
[  0   1   8  48 256]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   4  16  64 256]

(32, -64, 42, -11, 1)

x^4 - 11*x^3 + 42*x^2 - 64*x + 32

4*x^3 - 33*x^2 + 84*x - 64

x - 4

The square matrix is non-diagonalizable
