# Minimal Polynomial

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">陳政廷</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

### Overview

#### **多項式代入矩陣**
- 若 $p(x) = a_nx^n +a_{n-1}x^{n-1} + \cdots + a_0$ 是一個多項式，  
而 $A$ 為一矩陣  
則定義 $p(A) = a_nA^n +a_{n-1}A^{n-1} + \cdots + a_0I$。

#### **Cayley&ndash;Hamilton定理**:
- $A$ 為一個 $n\times n$ 階矩陣且 $p(t)$ 為 $A$ 的特徵多項式( $p(t)=\det(A-tI)$ )。將矩陣 $A$ 替換 $t$ 得到的矩陣多項式滿足 $p(A)=O$。

#### **最小多項式** $m_A(t)$:
 1. 滿足 $p(A)=O$ 的方程式中次數為最小者
 2. 最高次項係數為1

#### **最小多項式的重要性質**:
 1. $A$ 之所有的特徵值 $λ_i$ 皆使 $m_A(λ_i)=0$
 2. 若 $p(t)=(t-λ_1)^{m_1}\times(t-λ_2)^{m_2}\times\cdots\times(t-λ_k)^{m_k},m_{1}+m_{2}+\cdots+m_{k}=n$  
 則 $m_A(t)=(t-λ_1)^{d_1}\times(t-λ_2)^{d_2}\times\cdots\times(t-λ_k)^{d_k}, 1 \leq d_i \leq m_i$, $\forall i$ 
 3. $A$ 可對角化 $\iff$ $m_A(t)=(t-λ_1)\times(t-λ_2)\times\cdots\times(t-λ_k)$；  i.e 最小多項式沒有重根

### Algorithm

1. Compute $I,A,\ldots,A^{n}$ and flaten them into vectors in $\mathbb{R}^{n^2}$.  
2. Find the smallest $k$ such that $\{I,A,\ldots,A^k\}$ is dependent.  
3. Suppose $A = \begin{bmatrix}a_{i,j}\end{bmatrix}$.  
You may flatten them as a vector $f(A) = (a_{1,1},\ldots, a_{1,n},a_{2,1}\ldots,a_{n,n})$ in $\mathbb{R}^{n^2}$  
4. Create a huge matrix $H$ whose columns are $f(I),f(A),\ldots,f(A^{n})$ and  
do Gaussian elimination on $H$.
5. Find the minimum $k$ such that $\{f(I),f(A),\ldots,f(A^k)\}$ is dependent.  
6. Find coefficients so that $a_kf(A^k)+\ldots a_0f(I)=0$ and $a_k=1$.  
7. Thus $a_kA^k+\ldots a_0I=O$ and $m(t)=a_kt^k+\cdots+a_0$ is the minimal polynomial.




### Explanation
判斷$A_{n\times n}$是否可對角化

>$p(t)=det(A-tI)=(t-λ_1)^{m_1}\times(t-λ_2)^{m_2}\times\cdots\times(t-λ_k)^{m_k}$ 

找出$p(t)$的最小多項式$m_A(t)$使得$m_A(A)=0$  
如果$m_A(t)$中$(t-λ_i)$的次數皆為1次，則A為可對角化  
如果$m_A(t)$中其中一項$(t-λ_i)^k,2\leq k$，則A為不可對角化



##### Implementation

In [1]:
def minimalpolynomial(data):
    """
    Input:
        data:  給定一方陣A
    Output:
        Output 最小多項式 m_A(t) 中沒有重根，則方陣A為可對角化。
    """
    data.change_ring(QQ)
    m,n = data.dimensions()
    if (m == n):
        I = identity_matrix(n)                                     #單位矩陣
        flattened_I = [I[i,j] for i in range(m) for j in range(n)] #攤平單位矩陣
        flattened_data = [flattened_I] #將I存成[I]
   
        for k in range(1,m+1):
            data_i=data^k
            flattened_data_i= [data_i[i,j] for i in range(m) for j in range(n)] #data^k矩陣攤平
            flattened_data.append(flattened_data_i) #將矩陣變為[I,data^1,...,data^k]
        M = matrix(flattened_data).transpose() 
        show(M)
       
        r = M.rank()
         
        sliced_M = M[:,0:r+1]
        show(sliced_M)
        factor=sliced_M.right_kernel()
        show(factor.basis()[0])
        A=matrix(factor.basis()[0])
        
        
        
        poly=0 
        for k in range(0,r+1):    #取出係數將其變為一多項式
            item=x^k*A[0,k]
            poly+=item
        if(A[0,r]<0):             #讓首項系數為1
            poly*=-1
        return poly
           
    else:
        print'data is not square matrix'

def diagonalizable(data):
    poly=minimalpolynomial(data)
    show(poly)
    polyprime=poly.derivative()
    show(polyprime)
    poly.gcd(polyprime)
    show(poly.gcd(polyprime))
    if (poly.gcd(polyprime)==1):
        print'The square matrix is diagonalizable'   # If p and pprime has common factor other than 1, then p is not square free
    else:
        print'The square matrix is non-diagonalizable'

        
        


##### Examples

In [2]:
### diagonalizable
data= matrix([[3,-3,2],[-1,5,-2],[-1,3,0]])
print "Matrix:"
show(data)
print "---"
diagonalizable(data)


Matrix:


[ 3 -3  2]
[-1  5 -2]
[-1  3  0]

---


[  1   3  10  36]
[  0  -3 -18 -84]
[  0   2  12  56]
[  0  -1  -6 -28]
[  1   5  22  92]
[  0  -2 -12 -56]
[  0  -1  -6 -28]
[  0   3  18  84]
[  1   0  -8 -48]

[  1   3  10]
[  0  -3 -18]
[  0   2  12]
[  0  -1  -6]
[  1   5  22]
[  0  -2 -12]
[  0  -1  -6]
[  0   3  18]
[  1   0  -8]

(8, -6, 1)

x^2 - 6*x + 8

2*x - 6

1

The square matrix is diagonalizable


In [3]:
### random matrix diagonalizable
import numpy as np
data= matrix(np.random.randint(0,100,[4,4]))
print "Matrix:"
show(data)
print "---"
diagonalizable(data)

Matrix:


[16 17 85 80]
[54 95 63 62]
[92 82 21 30]
[17 30 89 74]

---


[        1        16     10354   2000122 468850888]
[        0        17     11257   2499105 580081175]
[        0        85     11336   2788893 623279608]
[        0        80     10804   2665830 595892480]
[        0        54     12844   3007798 685429428]
[        1        95     16969   3759155 852325901]
[        0        63     17416   4011755 918228560]
[        0        62     16688   3836990 877981360]
[        0        92      8342   2521098 547877358]
[        0        82     11976   3058308 683480468]
[        1        21     16097   3162761 742568597]
[        0        30     15294   3024538 710001578]
[        0        17     11338   2142788 507180048]
[        0        30     12657   2702921 627465001]
[        0        89     11790   3020285 672750650]
[        1        74     11366   2886558 643217984]

[        1        16     10354   2000122 468850888]
[        0        17     11257   2499105 580081175]
[        0        85     11336   2788893 623279608]
[        0        80     10804   2665830 595892480]
[        0        54     12844   3007798 685429428]
[        1        95     16969   3759155 852325901]
[        0        63     17416   4011755 918228560]
[        0        62     16688   3836990 877981360]
[        0        92      8342   2521098 547877358]
[        0        82     11976   3058308 683480468]
[        1        21     16097   3162761 742568597]
[        0        30     15294   3024538 710001578]
[        0        17     11338   2142788 507180048]
[        0        30     12657   2702921 627465001]
[        0        89     11790   3020285 672750650]
[        1        74     11366   2886558 643217984]

(3113554, 249790, -6175, -206, 1)

x^4 - 206*x^3 - 6175*x^2 + 249790*x + 3113554

4*x^3 - 618*x^2 - 12350*x + 249790

1

The square matrix is diagonalizable


In [4]:
### non-diagonalizable
data = matrix([[1,-1],[1,3]])
print "Matrix:"
show(data)
print "---"
diagonalizable(data)

Matrix:


[ 1 -1]
[ 1  3]

---


[ 1  1  0]
[ 0 -1 -4]
[ 0  1  4]
[ 1  3  8]

[ 1  1  0]
[ 0 -1 -4]
[ 0  1  4]
[ 1  3  8]

(4, -4, 1)

x^2 - 4*x + 4

2*x - 4

2*x - 4

The square matrix is non-diagonalizable


In [5]:
### non-diagonalizable  
data =matrix([[1,0,0,0],[0,2,0,0],[0,0,4,1],[0,0,0,4]])
print "Matrix:"
show(data)
print "---"
diagonalizable(data)


Matrix:


[1 0 0 0]
[0 2 0 0]
[0 0 4 1]
[0 0 0 4]

---


[  1   1   1   1   1]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   2   4   8  16]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   4  16  64 256]
[  0   1   8  48 256]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   4  16  64 256]

[  1   1   1   1   1]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   2   4   8  16]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   4  16  64 256]
[  0   1   8  48 256]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  0   0   0   0   0]
[  1   4  16  64 256]

(32, -64, 42, -11, 1)

x^4 - 11*x^3 + 42*x^2 - 64*x + 32

4*x^3 - 33*x^2 + 84*x - 64

x - 4

The square matrix is non-diagonalizable
